// Generated by CoffeeScript 1.9.3
(function() {
  var _tensify, a_an, choose, tensify, unique,
    slice = [].slice;

  _tensify = require("tensify");

  tensify = function(verbial_phrase, how) {
    var more, verb, words;
    words = verbial_phrase.split(" ");
    verb = words[0], more = 2 <= words.length ? slice.call(words, 1) : [];
    return [_tensify(verb)[how]].concat(slice.call(more)).join(" ");
  };

  a_an = function(what) {
    if (what.match(/^\s*[aeiou]/)) {
      return "an " + what;
    } else {
      return "a " + what;
    }
  };

  unique = require("array-unique");

  choose = function(arr) {
    return arr[~~(Math.random() * arr.length)];
  };

  String.prototype.ucfirst = function() {
    return this.charAt(0).toUpperCase() + this.slice(1);
  };

  module.exports = function(subject) {
    var i, j, o, results, some_action, some_adjectives;
    var out = ''
    o = function(text) {
      out = out.concat(text).concat('\n')
    };
    o("Hey, look, " + (a_an(subject.singular)) + "!");
    o("");
    o("I think " + subject.plural + " are...\n   " + (subject.adjectives.join("\n   ")));
    o("");
    o("What do " + subject.plural + " do? They...\n   " + (subject.verbs.join("\n   ")));
    some_adjectives = function() {
      return unique((function() {
        var i, ref, results;
        results = [];
        for (i = 0, ref = Math.random() * 3; 0 <= ref ? i <= ref : i >= ref; 0 <= ref ? i++ : i--) {
          results.push(choose(subject.adjectives));
        }
        return results;
      })());
    };
    some_action = function() {
      return choose(subject.verbs);
    };
    o("");
    for (i = 0; i <= 5; i++) {
      o("There is " + (a_an(some_adjectives().join(", "))) + " " + subject.singular + ".");
    }
    o("");
    results = [];
    for (j = 0; j <= 5; j++) {
      results.push(o(((a_an(some_adjectives().join(", "))) + " " + subject.singular + " " + (tensify(some_action(), "past")) + ".").ucfirst()));
    }
    return out
  };

}).call(this);
